name: Grammar Check

on: [pull_request]

jobs:
  languagetool:
    name: Check Grammar
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: LanguageTool with Reviewdog
        uses: reviewdog/action-languagetool@v1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            reporter: github-pr-review
            level: warning
            language: ru-RU
            disabled_rules: EN_QUOTES